name: Feature Request
description: Suggest a new feature for Family Meal Planner
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like to see
      placeholder: I would like to...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the app does this feature relate to?
      options:
        - Meal Planning
        - Recipe Management
        - Shopping List
        - User Authentication
        - Mobile UI/UX
        - PWA Features
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature help you and your family?
      placeholder: This would help me...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any mockups, examples, or additional context
      placeholder: Screenshots, links to similar features, etc.
